### ISSUE TITLE
Demo Widget & Mapa

### ISSUE THREAD

**Issue by clcanela** [designomx/ft_widget.tooth.me#3]
Sitio demo

**Comment by clcanela** [comment]
Demo:
https://tooth.me/widgets/foodtrucks/test/
Me faltaría un bullet para el ícono del mapa (o le dejamos el default?)
y qué harían cada uno de los botones que salen debajo del badge en el sidebar

**Comment by designomx** [comment]
![pin_solo](https://cloud.githubusercontent.com/assets/6846840/12280461/aca8319e-b953-11e5-8bdd-7de6ca9f0317.png)

**Comment by clcanela** [comment]
Si está cerrado:
- agregar también la clase de no location
- El widget no te deja hacer link al mapa

**Comment by clcanela** [comment]
http://stagefoodtrucks.tooth.me/
